# Generated by Django 5.0.4 on 2024-05-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('cancel_order', 'Can cancel Order'), ('view_history', 'can view history')]},
        ),
    ]
